apiVersion: batch/v1
kind: Job
metadata:
  name: firstwait10m
spec:
  template:
    spec:
      containers:
      - name: firstwait10m
        image: debian:latest
        command: ["sleep",  "600"]
      restartPolicy: Never
  backoffLimit: 4