apiVersion: batch/v1
kind: Job
metadata:
  name: wait10m
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
      - name: wait10m
        image: debian:latest
        command: ["sleep",  "600"]
      restartPolicy: Never
  backoffLimit: 4