apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      labels:
        job-label: test-job
    spec:
      restartPolicy: Never
      containers:
        - name: test-job
          image: debian:bookworm-slim
          command: ["sleep", {{ quote .Values.deleteHook.sleepDuration }}]
  backoffLimit: 1